Githubname: Github Neoload Test v1

on:
  workflow_dispatch:

jobs:
  build:
    name: Neoload CLI github action
    runs-on: ubuntu-latest
    steps:

      - name: "Install Neoload CLI"
        run: pip3 install -U neoload

      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: "Prepare Neoload Test"
        env:
          NEOLOAD_LOGIN: ${{secrets.NEOLOAD_LOGIN}}
        run: neoload login $NEOLOAD_LOGIN

      - name: Use workspace
        run: neoload workspace use "K&D - I and I"
        
      - name: "Do Test Settings"
        run: neoload test-settings --zone HtRnd --lgs 1 --scenario 'scenario1' createorpatch "NeoGithub_test_01"

      - name: "Upload Project"
        run: neoload Project --path Regions_QA.zip upload Github_Test_01

      - name: "Neoload run test"
        run: >
          neoload --batch run
          --detached
          --external-url 
